tablist:
  updateTab: 60
  updatePrefix: 600

  header:
    - ''
    - ''
    - ''
    - ''

  footer:
    - ''
    - ''
    - ''
    - ''

scoreboard:
  update: 20
  lines:
    - ''
    - ''
    - ''
    - ''
    - ''

chat:
  format: '%prefix% %player%&8: &7%message%'
