name: SimpleTablist
version: COMMISSION
main: de.waischbrot.simpletablist.Main
api-version: 1.17
authors: [ Waischbrot ]
description: Simple Tablist Plugin for handling hex color codes & Luckperms prefixes
website: https://waischbrot.de
depend:
  - LuckPerms
  - PlaceholderAPI

commands:
  scoreboard:
    description: Toggle Scoreboard
    usage: /scoreboard OR /scoreboard <Player>
    tablist:
      description: TabList settings
      usage: /tablist reload
