name: SimpleTablist
version: COMMISSION
main: de.waischbrot.simpletablist.Main
api-version: 1.17
authors: [ Waischbrot ]
description: Simple Tablist Plugin for handling hex color codes & Luckperms prefixes
website: https://waischbrot.de
softdepend:
  - PlaceholderAPI
depend:
  - LuckPerms
commands:
  stl:
    usage: /stl <reload>
    description: Get plugin help or reload the config.
